name: pointer_interceptor
description: A widget to prevent clicks from being swallowed by underlying HtmlElementViews on the web.
repository: https://github.com/flutter/packages/tree/main/packages/pointer_interceptor/pointer_interceptor
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+pointer_interceptor%22
version: 0.9.3+7
# while transitioning to federated structure, removed ability to published temporarily.
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

flutter:
  plugin:
    implements: pointer_interceptor_platform_interface
    platforms:
      web:
        default_package: pointer_interceptor_web
      ios:
        default_package: pointer_interceptor_ios

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  pointer_interceptor_ios:
    path: ../pointer_interceptor_ios
  pointer_interceptor_platform_interface: ^0.10.0
  pointer_interceptor_web:
    path: ../pointer_interceptor_web

dev_dependencies:
  flutter_test:
    sdk: flutter

topics:
  - web
  - widgets
  - pointer-interceptor
