name: google_identity_services_web_example
description: An example for the google_identity_services_web package, OneTap.
publish_to: 'none'
version: 0.0.1

environment:
  flutter: ">=3.16.0"
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_identity_services_web:
    path: ../
  http: ">=0.13.0 <2.0.0"
  web: ">=0.3.0 <0.5.0"

dev_dependencies:
  build_runner: ^2.1.10 # To extract README excerpts only.
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
