name: google_maps_flutter_web_integration_tests
publish_to: none

# Tests require flutter beta or greater to run.
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter_platform_interface:
    path: ../../google_maps_flutter_platform_interface
  google_maps_flutter_web:
    path: ../

dev_dependencies:
  build_runner: ^2.1.1
  flutter_test:
    sdk: flutter
  google_maps: ^6.1.0
  google_maps_flutter:
    path: ../../google_maps_flutter
  http: ">=0.13.0 <2.0.0"
  integration_test:
    sdk: flutter
  mockito: 5.4.3

dependency_overrides:
  # Override the google_maps_flutter dependency on google_maps_flutter_web.
  # TODO(ditman): Unwind the circular dependency. This will create problems
  # if we need to make a breaking change to google_maps_flutter_web.
  google_maps_flutter_web:
    path: ../
